name: Compile LaTeX Documents in Repository

on: [push]

jobs:
  build_individual_papers:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        paper:
          - dir: .
            tex_file: mac_fpga_workflow_instructions
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Python & Pygments
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'  # Ensure Python is installed
    - run: pip install pygments  # Install Pygments

    - name: Compile Paper
      uses: devinatkin/latex-action/compile_latex@main
      with:
        tex-file: ${{ matrix.paper.tex_file }}
        directory: ${{ matrix.paper.dir }}

    - name: Upload Paper PDF to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.paper.tex_file }}_paper_pdf
        path: ${{ matrix.paper.dir }}/*.pdf