name: Build LaTeX to HTML and publish to Pages

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        paper:
          - dir: .
            tex_file: mac_fpga_workflow_instructions

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Convert .tex to index.html
        run: |
            mkdir -p dist
            base="${{ matrix.paper.tex_file }}"
            pandoc "${{ matrix.paper.dir }}/${base}.tex" -s \
            --mathjax="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js" \
            -o "dist/index.html"


      - name: Disable Jekyll
        run: touch dist/.nojekyll

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
